apiVersion: v1
kind: Service
metadata:
  name: flask-api-last-service2
spec:
  selector:
    app: first-app-flask2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort